### ISSUE TITLE
Screen reader feedback of progress indicator

### ISSUE THREAD

**Issue by dkager** [daisy/pipeline-webui#102]
These are only my observations, not necessarily a bug. When running a long'ish job with dtbook-to-pef I notice two things:
1. The screen reader often speaks incremental numbers. First 1, 2, 3, ..., 7, 8. But as the job continues this rises to 20+. The constant repeating of these numbers hinders navigating the UI with speech a bit.
2. The progress bar is reported by the screen reader as "progress bar 97.3556634925753". Could that number be rounded to 2-3 decimals?

**Comment by josteinaj** [comment]
The progressbar has both `aria-valuenow` and `aria-valuetext` attributes. The aria-valuetext attribute is rounded to the nearest integer, so I thought that screen readers would only announce when that attribute changed.

The aria-valuenow attribute is the full decimal number which appearantly is what you are getting presented with. I could try to round aria-valuenow to only 1 or 2 decimals, and only update the attribute when the value has changed.

**Comment by dkager** [comment]
Thanks. I'm not too familiar with the aria attributes but this implementation sounds logical. Something to ping the screen reader developers about I think.

**Comment by bertfrees** [comment]
@dkager @josteinaj Is this issue fixed?

**Comment by dkager** [comment]
Seems fixed. Or rather, the web UI changed quite a bit and I don't see issues with the new one anymore.

**Comment by josteinaj** [comment]
It was fixed in 64f6c88a2eb14623c5a672259622ef2fbf19c6da but not tested until @dkager tested it now.
