### ISSUE TITLE
What's the send mail "from" address and can it be set?

### ISSUE THREAD

**Issue by joeha480** [daisy/pipeline-webui#105]
I know there's a field called "user name" in the e-mail settings, but it seems to be used only for authentication (even when authentication is turned off, by the way), but I need to set the "from" address for Pipeline e-mails, since only specific accounts are allowed to send mail from a server application under Office 365.

**Comment by josteinaj** [comment]
The "from" address seems to be set to the email of the currently logged in user:

https://github.com/daisy/pipeline-webui/blob/b26dbc6f47378ea52690adc0bcac25a6402ec9ae/app/controllers/Administrator.java#L286

**Comment by joeha480** [comment]
What about the forgotten password feature then?

**Comment by joeha480** [comment]
Ok, I think I understand how it works now. I created this issue instead: #106
