### ISSUE TITLE
Error while authenticating

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-webui#107]
When I want to use the web UI with a server that has authentication enabled, I go to Administrator settings, Pipeline 2 Web API, and then I'm asked for the Authentication ID and the Secret token. Both fields are red and show the message "An error occured while authenticating". I'm pretty sure the ID and secret token I filled in are correct because I'm using them with the CLI does work.

In the console I see messages like these:

```
[warn] o.a.h.i.c.DefaultHttpClient - Authentication error: Unable to respond to any of these challenges: {}
[error] application - [WS clientlib] http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2 failed:

null
```

Also, a few times the fields turned green all of a sudden, but then immediately after (after going to another browser tab and coming back) turned red again. Very weird.

I should also say that I'm running the server from a Docker container, and the web UI on the host, although that should not make a difference I think (also using the CLI from the host).

By the way, when the server can not be reached at all, you get a message, at the top of each page, saying "Unable to communicate with the Pipeline 2 Engine", which I think is quite useful. When the server can be reached but authentication fails, you don't get such a message, but it would be as useful.

PS: The web UI doesn't seem to support localfs=false. When I run a script I get error messages like:

```
    java.io.FileNotFoundException: /Users/bert/Library/Application Support/DAISY Pipeline 2 Web UI/jobs/3/context/ncc.html (No such file or directory)
    XC0011: Could not load file:/Users/bert/Library/Application%20Support/DAISY%20Pipeline%202%20Web%20UI/jobs/3/context/ncc.html
```

I'll create a separate issue for this.

**Comment by bertfrees** [comment]
> The web UI doesn't seem to support localfs=false.

This issue should have been fixed in https://github.com/daisy/pipeline-clientlib-java/commit/1184ab7e71a881e4390f2e43d9340a1f587a1ebe

**Comment by josteinaj** [comment]
Closed by #118

**Comment by bertfrees** [comment]
@josteinaj We're (Daniel Persson and I) experiencing exactly the same issue as the one described here. I can't figure out exactly which commit in https://github.com/daisy/pipeline-webui/pull/118, https://github.com/daisy/pipeline-clientlib-java/pull/18/commits or https://github.com/daisy/pipeline-clientlib-java/pull/21 has fixed this.

**Comment by bertfrees** [comment]
CC @kalaspuffar

**Comment by josteinaj** [comment]
Hi @bertfrees and @kalaspuffar. Unfortunately I won't have time to look into this (or the pipeline-webui project in general). I'm sorry.

If you patch the code, you can make a new release by pushing to docker hub with a tag. Building for other targets than docker at this point will take some time to get working.
