### ISSUE TITLE
Add support for managing templates

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-webui#17]
Store, load, delete, etc. templates.

User permissions for templates.

~~blockedon daisy/pipeline-clientlib-java#4~~

**Comment by bertfrees** [comment]
See [mockup](https://projects.invisionapp.com/d/main#/projects/1178301)

**Comment by bertfrees** [comment]
Saving, loading, renaming, deleting and shared are now supported. Close issue?
