### ISSUE TITLE
Fix time displayed in job details

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-webui#20]
Time created/started/finished is comparing server time and browser time. Times should be adjusted so that there is no apparent difference between server- and browser-time.

**Comment by josteinaj** [comment]
Also, "time finished" is set to 1st January 1970 until the job is finished. It should be displayed as "not yet" instead.

**Comment by josteinaj** [comment]
I don't think adjusting client time to server time should be an issue; we can probably assume that both the client and server is set to the same time (different timezones ok as long as it's the same utc).

Also I don't see the 1st January 1970 issue anymore so I think this issue can be closed.

**Comment by bertfrees** [comment]
I think also the counting starts as of when the job was *created*, which is not the same as when the job was *submitted*. Is that right? Also when you restart a job, the counting starts from when the *original* job was created I think.

**Comment by josteinaj** [comment]
The dates are "fuzzy". The created, started and finished dates are generated by the server. The current client time is compared with those dates to create the fuzzy dates "X seconds ago", "X months ago", "Not yet", etc. Nothing bad will happen if there is a different time on the server and on the client but you might end up with created/started times saying "not yet" while the job is clearly started, or getting "created 3 hours ago" right after the job is created.

What I was originally thinking about with this issue was to send the current server time (UNIX UTC) to the browser so that the browser could compensate for any time discrepancies.

There's no difference between "created" and "submitted". There's a "started" which is the time when the job goes from an IDLE state to a RUNNING state. The finished date is when the job goes from a RUNNING state to a DONE/ERROR/VALIDATION_FAIL state.

The counting in the jobs list uses the created date and is not reset when you create a new job. I've changed that for the next version so that it uses the started date instead when sorting the list (with a fallback to the created date), so that if you restart an old job it will be put at the top of the jobs list.
