### ISSUE TITLE
Selection button state not clear (to screen reader software)

### ISSUE THREAD

**Issue by dkager** [daisy/pipeline-webui#27]
Steps to reproduce:
* New job.
* Upload a file.
* Choose a script.
* Show more options.

The `Yes` and `No` buttons are read correctly. However, there is no way of telling which is selected. Suggestion: use standard radio buttons instead or add something like "selected" to the label when something is selected.

**Comment by josteinaj** [comment]
Thanks for the report, that definitely sounds like it needs fixing. I'm marking this as a bug.

**Comment by josteinaj** [comment]
I've replaced booleans with checkboxes in the latest version. That should fix this.

**Comment by dkager** [comment]
Awesome! I’ll test when it’s up.

**Comment by dkager** [comment]
I can confirm this fixed. Good to close for me.

**Comment by josteinaj** [comment]
Great. Thanks for reporting and confirming fix.
