### ISSUE TITLE
Ability to set the nicename of a job

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-webui#33]
...maybe even change it after the job is created

**Comment by josteinaj** [comment]
I'm not really sure if this is really needed. Do we have it as a requirement somewhere? The Web UI currently generates a nicename that I think is sufficient.

**Comment by bertfrees** [comment]
We don't have it as a requirement AFAIK. It was an idea from you I think.

**Comment by josteinaj** [comment]
Yeah probably. I just close it and see if anybody protests.
