### ISSUE TITLE
Use the default values of script options that are now exposed by the web API

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-webui#34]
See https://github.com/daisy/pipeline-framework/pull/90/files

**Comment by josteinaj** [comment]
There are no current script that uses this feature. It would be easier to implement if there was a script that had a default value.

@bertfrees I think I'll wait with this until we have a script that uses this feature.

@usama49 if you have time, maybe we could have a look at adding default values to the scripts together? (alternatively @bertfrees if you want to do it that's fine as well)

**Comment by josteinaj** [comment]
see: snaekobbi/issues#19 and snaekobbi/issues#20
