### ISSUE TITLE
Ability to download and upload templates

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-webui#38]
Something like this:

![2015-10-28 13 00 59](https://cloud.githubusercontent.com/assets/295481/10787892/2a3dc1ee-7d74-11e5-88e0-b5177f090c64.jpg)

The download would be the contents of the equivalent template directory on disk as a zip; i.e. a job.xml file and a context directory.

The upload must be either a zip and must follow the same folder structure as is used internally with the job.xml, context directory, etc. A descriptive error message should be displayed if the uploaded template is not valid.

Name collisions with other templates might be an issue as well - we could consider overwriting any pre-existing template with the same name. This would make the download-edit-upload iterations of editing a template manually easier, although we don't know yet if someone will actually edit the templates that way. Editing a template might be done more easily by creating a new job based on a template, editing the inputs, then storing it as a template again. We could potentially have a "edit template" view as well which would essentially be the same as the "new job" view, except that there would be no "start job" button - only a "save template" button.

**Comment by bertfrees** [comment]
Alright. Sounds like a good idea.

The downloading/uploading is for backup purposes I assume? Do we already know this is a use case or should we wait until people are using it and ask for it?

Before overwriting I would always show a warning message. And also limit the overwrite function to the owner of the template maybe?

I have also been thinking about having pre-installed templates (more or less the same use case, except the templates are installed during the deploy script, not manually through a button). Would that be possible too you think? In order to make this work and to not cause trouble during upgrading etc., I think it would be a good idea to give these templates a special owner so that they can not be modified or deleted by anyone not even admins.

**Comment by josteinaj** [comment]
A use-case for downloading and uploading templates would be to share templates between instances of the Web UI. For instance, in production with everyone hosting their own servers - or even local installs, I could create a template on NLBs server and send it to someone at Nota for use on their server.

It might also be interesting if you need to access the files in the context of the template for some reason (maybe you don't have them locally).

I'm currently working on how to store the templates. The simplest solution would be to just treat them as jobs, but I would like to have a special template directory where it's easy to add and remove templates manually through the file system. That would allow pre-installed templates as you suggest, which I think is a great idea.

Ownership of templates is indeed an issue... How about using a folder structure like `[userid]-[userNicename]/[templateName]/` this to store the templates?:

```
templates/
├── 1-Jostein/
│   └── This is Josteins favourite template/
│       ├── context/
│       └── job.xml
├── 2-Bert/
│   └── This is Berts favourite template/
│       ├── context/
│       └── job.xml
└── shared/
    ├── Everybodys favourite template/
    │   ├── context/
    │   └── job.xml
    └── One template to rule them all/
        ├── context/
        └── job.xml
```

This should make it fairly easy to edit the templates directly from the file system, as well as allowing both "global templates" (available for all, only admins, or maybe nobody, can delete), as well as "user templates" (only user and admins can see, use, modify and delete).

They would not be stored in a database, but loaded as needed from disk.

wdyt?

**Comment by bertfrees** [comment]
So the owner information is captured in the directory structure? OK should work. I assume admins can also have private templates so they'd need some option to share templates? And I assume the "shared" directory would be used for templates that an admin shares, so if we'd want to support pre-installed templates that can not be modified by admins, we'd need another place for them (named "master" or "factory-settings" or something).

A consequence of your proposal is that two templates can have the same name if they have different owners (are in different folders), and potentially both visible for a certain user.

**Comment by josteinaj** [comment]
Right, I suppose we would need a separate directory for such bundled templates. From a usability perspective though; do we really want templates that cannot be deleted by admins? What if the upgrade script simply overwrites any pre-existing templates with the same name as it wants to install?

We could add support for letting admins hide templates I suppose (like is currently possible for scripts), but wouldn't that be a bit of a workaround for not being able to delete templates?

Is bundling templates during installation and upgrades even something we really need? Would it be less work to just update them manually when needed instead of adding it into the build/deploy system?

**Comment by bertfrees** [comment]
I don't know, it was just an idea. We can wait and see what people think. Maybe it's indeed not much work to do it manually.

Disallowing deletion of templates may indeed not be very good for usability. Simply overwriting is also not so great.

I don't understand the bit about hiding, was that important?

**Comment by josteinaj** [comment]
By hiding I meant that maybe you don't want all the bundled templates to be displayed if you're not using them (I didn't explain my thoughts there very well). That's the idea behind hiding scripts now; if there's a bunch of scripts you're never using, you can simply hide them.

By the way, templates that can't be deleted also means that you couldn't edit those templates I presume. So if you want to make a small change you need to fork the template. If we provide a special way of editing templates, we need to add a rule where those specific templates cannot be edited.

**Comment by bertfrees** [comment]
Right. Yeah I know there are some downsides. Let's just keep it as "an idea" for now.

**Comment by josteinaj** [comment]
Ok, sure. I might play around with implementing a "shared templates" directory in any case, so that it's easy to add templates manually (or map a network drive with templates). And in the future we can change its behaviour if we want to.

**Comment by josteinaj** [comment]
Support for downloading templates added (not deployed to test server yet). Will wait with adding support for uploading templates as I want to prioritize other things first. We can also consider whether the "download temple" button should be split into "download template context" and "download template XML", as the context might be reused separately.

**Comment by bertfrees** [comment]
> download template context vs. download template XML
What would be an example of a use case? Don't really understand.

**Comment by josteinaj** [comment]
The template context (or "job input files" as I will probably call them in the UI) is exactly the same folder structure as you uploaded when creating the template or job. Thus, it could be used to create a new job directly without unzipping/zipping.

However, the context does not include which script is selected, what the option values are etc.

Really, I'm not quite sure if downloading and uploading templates is that useful for most users at all. I suspect I implemented it just because it was easy to do, and invented a use-case after-the-fact :). Maybe I should just remove the download-button for now, and we'll see if someone requests the ability to download/upload templates later? The context will be available from finished jobs based on the template anyway.

![templates 2015-11-11](https://cloud.githubusercontent.com/assets/295481/11094145/607f702a-888e-11e5-95f8-6ccd0506e604.png)

**Comment by bertfrees** [comment]
OK got it.

Well, I can see at least one important use case for downloading/uploading, and that is for backup. This should only be done by admins. The other use case is sharing across server instances. This is the one you invented I guess?

Both use cases have not been requested explicitly, so I'm OK with hiding the functionality for now.

**Comment by josteinaj** [comment]
I'm marking this as *Done* since it will be possible to download the template input files in the next release.

**Comment by bertfrees** [comment]
Great. I'll close.
