### ISSUE TITLE
Ability to set the nicename of a template

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-webui#39]

**Comment by josteinaj** [comment]
For use-cases, see:
- snaekobbi/sprints#88
- snaekobbi/sprints#89

**Comment by joeha480** [comment]
I could not set the name of the template I created: It is called template 13 on the test server, and I tried to change it several times, both when it was private and when it was shared.

**Comment by josteinaj** [comment]
Interesting. Maybe there's some javascript issue. It works for me on Chromium 44 in Ubuntu, but I haven't tested anything else. Which browser are you using?

**Comment by joeha480** [comment]
Firefox

**Comment by josteinaj** [comment]
I can reproduce. It seems like the event listener on the save button is not registered properly maybe. I'll investigate.

**Comment by josteinaj** [comment]
I patched it so that now it works in Firefox. @joeha480 could you see if it's working for you now?

**Comment by joeha480** [comment]
It works for me too. Thanks! Nice job on the templates, by the way.
