### ISSUE TITLE
Group options on job creation page into content panes

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-webui#53]
Idea by @stesk, see https://botbot.me/freenode/snaekobbi/2015-12-10/?msg=55828972&page=1.

This seems useful, but would it be doable somehow? I don't think we don't want to make the Pipeline server aware of this grouping, but maybe we can have some kind of pattern in how we name options, which the web UI would then recognize? Or make the server copy attributes with foreign namespaces on XProc options to script XML from the web API. (Just thinking out loud.)

**Comment by josteinaj** [comment]
Interesting idea. I would think this would be interesting for other DP2 clients as well, not just the webui.

Copying all attributes in foreign namespaces sounds like a good idea. I would think that this grouping information would go in the `px` namespace though and I'm not sure if that's considered "foreign".

If we want to do this without making any changes in the engine, we could have a convention like "GROUPNAME: OPTIONNAME". So for instance, an option named "Page dimensions: Height" would be displayed as "Height" in a group named "Page dimensions".

**Comment by bertfrees** [comment]
OK, so I guess it would be doable one way or another. Let's see if it has a use case. The most obvious way to hide certain options for certain agencies is still by having agency-specific scripts, but if users find it acceptable (and useful) to be able to see other agency's options but don't want to be distracted by them, it good to know this is an alternative.

**Comment by josteinaj** [comment]
I've added support for grouping in the Web UI for grouping by splitting at the colon. I modified MTMs script for testing to this:

```xml
	<p:option name="keepCaptions" required="false" px:type="boolean" select="'true'">
        <p:documentation>
			<h2 px:role="name">Block elements: Keep imggroup without prodnote</h2>
        	<p px:role="desc">Keeps imggroup if value is true or if imagegroup contains a prodnote.</p>
        </p:documentation>
    </p:option>
	<p:option name="single-line-spacing" required="false" px:type="boolean" select="'true'">
        <p:documentation>
            <h2 px:role="name">Translation/formatting of text: Single line spacing</h2>
        	<p px:role="desc">Select 'No' for double line spacing.</p>
		</p:documentation>
    </p:option>
    <p:option name="rows" required="false" px:type="string" select="29">
        <p:documentation>
        	<h2 px:role="name">Page layout: Rows</h2>
        	<p px:role="desc">Number of rows.</p>
        </p:documentation>
    </p:option>
    <p:option name="cols" required="false" px:type="string" select="28">
        <p:documentation>
        	<h2 px:role="name">Page layout: Columns</h2>
        	<p px:role="desc">Number of characters on a row.</p>
        </p:documentation>
    </p:option>
    <p:option name="inner-margin" required="false" px:type="string" select="2">
        <p:documentation>
            <h2 px:role="name">Page layout: Inner margin</h2>
        	<p px:role="desc">The inner margin size, counted in characters.</p>
        </p:documentation>
    </p:option>
    <p:option name="outer-margin" required="false" px:type="string" select="2">
        <p:documentation>
			<h2 px:role="name">Page layout: Outer margin</h2>
			<p px:role="desc">The outer margin size, counted in characters.</p>
        </p:documentation>
    </p:option>
    <p:option name="include-obfl" required="false" px:type="boolean" select="'false'">
		<p:documentation>
			<h2 px:role="name">Include OBFL</h2>
			<p px:role="desc">Keeps the intermediary OBFL-file for debugging.</p>
		</p:documentation>
    </p:option>
    <p:option name="query" required="false" px:type="string" select="''">
    	<p:documentation>
    	    <h2 px:role="name">Advanced options</h2>
        	<p px:role="desc">Additional options using the following syntax: (name1:value1)(name2:value2)...</p>
    	</p:documentation>
    </p:option>
```

And here's the result:

![screencapture-localhost-9000-jobs-97-1452874337046](https://cloud.githubusercontent.com/assets/295481/12358033/9355e9ca-bbab-11e5-9bce-c47f258fe809.png)

The groups are sorted in order of occurence in the XML, so they can be re-ordered by the script author if desired.

**Comment by bertfrees** [comment]
Looks good!
