### ISSUE TITLE
No execution log and input files and parameters for finished jobs

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-webui#58]
Buttons "Download Detailed Log" and "Download input files" work, but the non-detailed log and option table are not rendered. Funny thing is that when the job is restarted, the log of the finished job is suddenly rendered which can of course be confusing.

**Comment by josteinaj** [comment]
Don't think I can reproduce this. Does it always happen for you?

**Comment by bertfrees** [comment]
It's on the test server. At least the second part has been so for a while already.

**Comment by josteinaj** [comment]
Strange. I'll try testing with Firefox when I have time.

**Comment by bertfrees** [comment]
I think maybe I get it only for old jobs (before an upgrade was made?)

**Comment by josteinaj** [comment]
Strange. It sounds like an issue I've experienced when sometimes when I create a new job, I get the input files for some other job already uploaded automatically. As if the new job number is the same as a previous job or something.

**Comment by josteinaj** [comment]
This is probably because of #61. The job is not present in the engine, probably it is being deleted when upgrading the engine. Why the input files and arguments are not showing I'm not sure why but it's probably related to the engine not being present in the engine.

**Comment by bertfrees** [comment]
Right.

**Comment by josteinaj** [comment]
And so I remember: you noted that "*when the job is restarted, the log of the finished job is suddenly rendered*", and I think that's because the log is saved by the webui and it's not replaced until there's a new log available even though the job has been restarted. The old `<log>`, `<results>` and `<messages>` in the web uis buffered job should probably be deleted when restarting the job.

**Comment by bertfrees** [comment]
Actually, IIRC, it was like this:

- first no log messages
- when you restart the job all previous messages are listed
- when the first new job message arrives, it replaces the first old message, the others are not removed
- when the second new job message arrives, it replaces the second old message
- etc.

Does that make sense?

**Comment by josteinaj** [comment]
Ok, thanks. Yeah that makes sense.

**Comment by josteinaj** [comment]
The job logs are not available from the engine either (`/ws/jobs/.../log`)...

**Comment by bertfrees** [comment]
That's the detailed log, right? Now it magically works again on the test server... I'm confused.

**Comment by josteinaj** [comment]
Yeah, I see it's working again now.

Could it have something to do with permissions when installing on the server?

**Comment by bertfrees** [comment]
Don't know... We've been using the same update script for a while.
