### ISSUE TITLE
Don't delete the webui job if the engine job is not deleted

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-webui#62]
If you try to delete a job that also exists in the engine, but the DELETE request to the engine fails, then don't delete the webui job. Rather display an error along the lines of "not able to delete job from the Pipeline 2 engine".

**Comment by bertfrees** [comment]
@josteinaj Also if a job is running, the engine can't delete the job (https://github.com/daisy/pipeline-framework/issues/76), so it also better to not remove it from the user interface, right? Does your commit also fix that?

**Comment by josteinaj** [comment]
Yes the commit should fix that as well, although I haven't tested it. If the DELETE request to the engine was successful, the deletion is assumed to be successful.

**Comment by bertfrees** [comment]
OK good. Then let's hope the engine doesn't accept the DELETE request if the job is running :)
