### ISSUE TITLE
Create distributable for Windows

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-webui#64]

**Comment by josteinaj** [comment]
Also, make it work on Windows. It currently doesn't work.

**Comment by josteinaj** [comment]
Released an installer for Windows right now, ready for testing:

https://oss.sonatype.org/content/repositories/releases/org/daisy/pipeline/webui/2.2.0/

**Comment by bertfrees** [comment]
CC @dkager

**Comment by bertfrees** [comment]
CC @jukkae @dkager
