### ISSUE TITLE
"ø" not parsed correctly from Web API

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-webui#69]
In this option:

```xml
<option default="25" desc="..." name="page-height" nicename="Layout: Arkhøyde" ordered="true" required="false" sequence="false" type="integer"/>
```

The nicename is rendered in the Web UI as `Arkh?yde`. The Web API seems to return the correct character so the problem is with either [pipeline-clientlib-java](/daisy/pipeline-clientlib-java) or with the Web UI.

**Comment by josteinaj** [comment]
Does not happen anymore. Maybe the file was saved with the wrong encoding or something.

**Comment by bertfrees** [comment]
I've seen a similar thing, maybe it was in the message feed when a braille character became a question mark.

**Comment by josteinaj** [comment]
Ok. Well, if the issue reappears we can reopen it.

**Comment by bertfrees** [comment]
Job 3209 is where I saw it.
