### ISSUE TITLE
Fix whitespace in markdown descriptions

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-webui#70]

**Comment by josteinaj** [comment]
I think this is an engine issue. The XML returned from the engine does not preserve the newlines. And the scripts do contain `xml:space="preserve"`.

**Comment by bertfrees** [comment]
Maybe add a unit test for https://github.com/daisy/pipeline-framework/commit/f5d94b08e46a15184c35e8abe9536602e31a598e? Maybe one that fires up the web API and makes HTTP calls using clientlib-java-http (or the PipelineClient from pipeline-it, not sure what the difference is)? Been thinking about that.

**Comment by josteinaj** [comment]
Yes, I agree. For now though I just want to prioritize getting a new Web UI version ready first so I won't have time to look at this until end of March. The test should go in the pipeline-framework repo I think.

**Comment by josteinaj** [comment]
Although I was unable to create a unit test in clientlib-java (and I haven't looked into creating a test in framework-core), I have tested that https://github.com/daisy/pipeline-framework/commit/f5d94b08e46a15184c35e8abe9536602e31a598e does indeed fix this issue. I also added `xml:space` to all the `px:type="desc"`s in mod-braille: https://github.com/daisy/pipeline-mod-braille/commit/e8b406e6f20a73dffe5d0910abe6d9ca39b4000f

I'll leave this issue open until a new version of framework-core and mod-braille is deployed and tested with the snaekobbi system.
