### ISSUE TITLE
Job status in web UI should better reflect actual status in engine

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-webui#74]
For example:

- For jobs listed as "running" it should be checked whether they are actually still running. For instance if the engine was restarted in the middle of a job it's probably not running anymore when the engine comes back online. This can be very confusing. The job should probably say "Failed" or maybe "Cancelled" or something.

- Related: When a job is deleted in the web UI it shouldn't be removed from the list until it is actually gone in the engine: https://github.com/daisy/pipeline-webui/issues/62

Also related: https://github.com/daisy/pipeline-webui/issues/61

**Comment by josteinaj** [comment]
The first issue where they have the state "running" permanently I believe to be an issue with the engine. I haven't looked into it for a while though.

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-framework/issues/105.

**Comment by josteinaj** [comment]
I'm closing this one as all the issues mentioned have separate issues.
