### ISSUE TITLE
10MB upload limit

### ISSUE THREAD

**Issue by KariRudjord** [daisy/pipeline-webui#96]
An error message appear when trying to produce a large EPUB (29.4 MB) (NLB 556972). Error message: "Request Entity Too Large".  Are there any file size restrictions? @josteinaj

**Comment by josteinaj** [comment]
There seems to be a restriction at 10 MB. It may have been introduced when I upgraded to Play Framework 2.x a while back.

The solution is to add this to application.conf:

```
play.http.parser.maxDiskBuffer = 1G
```
