### ISSUE TITLE
Version is "dev" instead of "2.4.0" on windows

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-webui#97]

**Comment by jukkae** [comment]
Installed from 2.4.0 installer downloaded from Sonatype. Before installing, I uninstalled the old version and manually deleted %APPDATA%\Roaming\Daisy Pipeline 2 Web UI\ (or whatever the folder was, not at Windows box right now.)

**Comment by josteinaj** [comment]
Fixed in this commit: https://github.com/daisy/pipeline-webui/commit/1cd800e46bc9e16b90daf4c15e4edd1139b36861

But let's wait with closing this one until you've been able to test a new webui version.
